### PR TITLE
changed commands

### PR DESCRIPTION
**Pull request by unseenmagik**
Changed the base commands to include `cp` before the command. 
Stops interaction with core red commands. 
Also added context to help menu for `cpnumber`

### CODE REVIEW

**Comment by unseenmagik** [comment]
corrected a typo

**Comment by TurnrDev** [comment]
I would have done this with command groups but this is good enough for now :+1:

**Comment by unseenmagik** [comment]
I will also look at grouping but this was a quick fix for now. 

Many Thanks
Ben

**Comment by TurnrDev** [comment]
Thanks for participating Ben :+1:

**Pull request merged**
